### ISSUE TITLE
黑苹果

### ISSUE THREAD

**Issue by Snowfly-Guo** [ic005k/ALC256#2]
外放可以调节音量 但是没有声音；
3.5mm的耳机有声音但是音乐声大人声小 还伴着有嘈杂声

**Comment by ic005k** [comment]
具体的机型是？
这个ALC256主要是针对戴尔机型，对于其它的机型，可能会存在问题。

**Comment by Snowfly-Guo** [comment]
@ic005k 机械革命S2 
我想我在研究研究吧 
谢谢你的回答

**Comment by zhangchenna** [comment]
dell 台式 使用 后还是无法驱动  alc3246
